### ISSUE TITLE
Prefer to mute (for now) instead of ban immediately.

### ISSUE THREAD

**Issue by TheDuckCow** [StandingPadAnimations/MCprep-Helpful-Horse#1]
Eventually I think we can switch to kicking instead of banning, and even better if we can have it limit to auto delete the messages if they are the same in. multiple channels AND they contain any link (anything with `http://` or `https://`).

It would also be great if we can add the bot to the Moderator #staff-chat channel so it posts messages there whenever it takes an action, similar to how the existing antispam bot does.

**Comment by StandingPadAnimations** [comment]
Closing this for now, but I have yet to confirm if any messages are send to the staff chat
