### ISSUE TITLE
Contributor readme!

### ISSUE THREAD

**Issue by TheDuckCow** [StandingPadAnimations/MCprep-Helpful-Horse#2]
Would love to also be able to test this out and understand how to deploy (and if there are any steps that would give away "secrets", then you can leave out and instead mention "contact owners for XYZ", e.g. if there's a secret key or something involved).

Useful things to cover:

- How to initialize and get things running locally (totally OK if this just links out to some generic article)
- What steps it takes to deply
- Any pre-deploy testing steps one can do, to make sure everything is working.

Also if you're willing to grant me contributor access, then I could work in other branches on this same repo without having to fork, I think that makes it cleaner!

**Comment by StandingPadAnimations** [comment]
The only secret thing is the token for the bot, but it can be substituted with another bot token. I'll make a guide on how to run this locally

**Comment by StandingPadAnimations** [comment]
A readme has been added with all the information needed. I've also added you as a contributor

**Comment by TheDuckCow** [comment]
Great thanks! Closing this now
