### ISSUE TITLE
Ignore discord links

### ISSUE THREAD

**Issue by TheDuckCow** [StandingPadAnimations/MCprep-Helpful-Horse#3]
See [this message here](https://discord.com/channels/737871405349339232/765969163755716639/986186516940353566), it seems right now anytime someone posts more than one photo, it counts it as spamming.

We should ignore any official discord links for spam purposes:
```
https://discord.com/
https://cdn.discordapp.com/
```

Though it also makes me wonder - right now is the "no spam" simply checking if the same user posted multiple times in a row? or is it trying to check for the same message sent? If the second, I'm confused why in the scenario above posting two different images triggered the warning.

**Comment by StandingPadAnimations** [comment]
This has now been added
